"""nullable

Revision ID: 16b4a243d41d
Revises: 2351a64b05ef
Create Date: 2015-04-01 10:55:03.054248

"""

# revision identifiers, used by Alembic.
revision = '16b4a243d41d'
down_revision = '2351a64b05ef'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('achievements_rewards', 'achievement_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('achievements_rewards', 'reward_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('goals', 'achievement_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goals', 'achievement_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('achievements_rewards', 'reward_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('achievements_rewards', 'achievement_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
