"""deprecate goal name_translation

Revision ID: 39caab1445ec
Revises: 3740c3deb378
Create Date: 2015-09-25 13:46:17.770482

"""

# revision identifiers, used by Alembic.
revision = '39caab1445ec'
down_revision = '3740c3deb378'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goals', 'name_translation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goals', 'name_translation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
