"""has_been_pushed

Revision ID: 2012674516fc
Revises: 62026366cd60
Create Date: 2017-03-08 17:44:02.214248

"""

# revision identifiers, used by Alembic.
revision = '2012674516fc'
down_revision = '62026366cd60'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_messages', sa.Column('has_been_pushed', sa.Boolean(), nullable=False, server_default='1'))
    op.create_index(op.f('ix_user_messages_has_been_pushed'), 'user_messages', ['has_been_pushed'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_messages_has_been_pushed'), table_name='user_messages')
    op.drop_column('user_messages', 'has_been_pushed')
    ### end Alembic commands ###
