"""additional_public_data

Revision ID: 3512efb5496d
Revises: 
Create Date: 2016-07-21 13:30:45.257569

"""

# revision identifiers, used by Alembic.
revision = '3512efb5496d'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('additional_public_data', sa.JSON(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'additional_public_data')
    ### end Alembic commands ###
