"""goal_triggers_achievement_date

Revision ID: 87dfedb58883
Revises: 65c7a32b7322
Create Date: 2017-02-08 15:59:53.780748

"""

# revision identifiers, used by Alembic.
revision = '87dfedb58883'
down_revision = '65c7a32b7322'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal_trigger_executions', sa.Column('achievement_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_goal_trigger_executions_achievement_date'), 'goal_trigger_executions', ['achievement_date'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goal_trigger_executions_achievement_date'), table_name='goal_trigger_executions')
    op.drop_column('goal_trigger_executions', 'achievement_date')
    ### end Alembic commands ###
