"""Tasks

Revision ID: 8b935f06690c
Revises: 2012674516fc
Create Date: 2017-05-11 18:41:59.178033

"""

# revision identifiers, used by Alembic.
revision = '8b935f06690c'
down_revision = '2012674516fc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('entry_name', sa.String(length=100), nullable=True),
        sa.Column('task_name', sa.String(length=100), nullable=False),
        sa.Column('config', sa.JSON(), nullable=True),
        sa.Column('cron', sa.String(length=100), nullable=True),
        sa.Column('is_removed', sa.Boolean(), nullable=False),
        sa.Column('is_auto_created', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_entry_name'), 'tasks', ['entry_name'], unique=False)
    op.create_index(op.f('ix_tasks_is_auto_created'), 'tasks', ['is_auto_created'], unique=False)
    op.create_index(op.f('ix_tasks_is_removed'), 'tasks', ['is_removed'], unique=False)
    op.create_index(op.f('ix_tasks_task_name'), 'tasks', ['task_name'], unique=False)
    op.create_table('taskexecutions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('task_id', sa.Integer(), nullable=False),
        sa.Column('planned_at', sa.DateTime(), nullable=False),
        sa.Column('locked_at', sa.DateTime(), nullable=True),
        sa.Column('finished_at', sa.DateTime(), nullable=True),
        sa.Column('canceled_at', sa.DateTime(), nullable=True),
        sa.Column('log', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_taskexecutions_task_id_tasks'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_taskexecutions'))
    )
    op.create_index(op.f('ix_taskexecutions_canceled_at'), 'taskexecutions', ['canceled_at'], unique=False)
    op.create_index(op.f('ix_taskexecutions_finished_at'), 'taskexecutions', ['finished_at'], unique=False)
    op.create_index(op.f('ix_taskexecutions_locked_at'), 'taskexecutions', ['locked_at'], unique=False)
    op.create_index(op.f('ix_taskexecutions_planned_at'), 'taskexecutions', ['planned_at'], unique=False)
    op.create_index(op.f('ix_taskexecutions_task_id'), 'taskexecutions', ['task_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taskexecutions_task_id'), table_name='taskexecutions')
    op.drop_index(op.f('ix_taskexecutions_planned_at'), table_name='taskexecutions')
    op.drop_index(op.f('ix_taskexecutions_locked_at'), table_name='taskexecutions')
    op.drop_index(op.f('ix_taskexecutions_finished_at'), table_name='taskexecutions')
    op.drop_index(op.f('ix_taskexecutions_canceled_at'), table_name='taskexecutions')
    op.drop_table('taskexecutions')
    op.drop_index(op.f('ix_tasks_task_name'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_is_removed'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_is_auto_created'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_entry_name'), table_name='tasks')
    op.drop_table('tasks')
    ### end Alembic commands ###
