"""force password change

Revision ID: 8e65de1ed535
Revises: 2012674516fc
Create Date: 2017-05-04 14:39:30.110799

"""

# revision identifiers, used by Alembic.
revision = '8e65de1ed535'
down_revision = '2012674516fc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_users', sa.Column('force_password_change', sa.Boolean(), server_default='0', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_users', 'force_password_change')
    ### end Alembic commands ###
