"""task_success

Revision ID: 902a80a786e8
Revises: cc8f9f50802f
Create Date: 2017-05-14 16:18:58.009078

"""

# revision identifiers, used by Alembic.
revision = '902a80a786e8'
down_revision = 'cc8f9f50802f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskexecutions', sa.Column('success', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_taskexecutions_success'), 'taskexecutions', ['success'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taskexecutions_success'), table_name='taskexecutions')
    op.drop_column('taskexecutions', 'success')
    ### end Alembic commands ###
