"""task_usermodified

Revision ID: cc8f9f50802f
Revises: 8b935f06690c
Create Date: 2017-05-11 18:46:09.764821

"""

# revision identifiers, used by Alembic.
revision = 'cc8f9f50802f'
down_revision = '8b935f06690c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_user_modified', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_tasks_is_user_modified'), 'tasks', ['is_user_modified'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_is_user_modified'), table_name='tasks')
    op.drop_column('tasks', 'is_user_modified')
    ### end Alembic commands ###
