"""grouptype_relevance2

Revision ID: e41a1c7304bb
Revises: e8799ed00992
Create Date: 2017-05-30 12:16:00.979845

"""

# revision identifiers, used by Alembic.
revision = 'e41a1c7304bb'
down_revision = 'e8799ed00992'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")
    op.execute("ALTER TYPE relevance_types ADD value 'groups' after 'global'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DELETE FROM pg_enum
        WHERE enumlabel = 'groups'
        AND enumtypid = (
          SELECT oid FROM pg_type WHERE typname = 'relevance_types'
        )
    """)
    # ### end Alembic commands ###
